config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  constraints CourierRouteConstraint.new do
    root to: "pages#courier_home"
  end

  constraints AuthorizerRouteConstraint.new do
    root to: "pages#authorizer_dashboard"
  end

  constraints SupervisorRouteConstraint.new do
    root to: "pages#supervisor_dashboard"
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :applications

  delete "attachments/:id", to: "applications#delete_image_attachment"

  delete "applications/attachments/:id", to: "applications#delete_attachment_collection"

  mount ActionCable.server => "/cable"
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :status, optional: true
  belongs_to :timeslot, optional: true
  belongs_to :user, optional: true
  belongs_to :region, optional: true
  belongs_to :refusereason, optional: true
  belongs_to :rejectreason, optional: true

  has_many_attached :agreement_photos
  has_one_attached :loan_agreement
  has_one_attached :asp_agreement
  has_one_attached :third_party_agreement
  has_one_attached :pd_agreement
  has_one_attached :passport_photo
  has_one_attached :registration
  has_one_attached :client_passport
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/refusereason.rb
class Refusereason < ApplicationRecord
  has_many :applications
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :applications
end

app/models/rejectreason.rb
class Rejectreason < ApplicationRecord
  has_many :applications
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :applications
end

app/models/timeslot.rb
class Timeslot < ApplicationRecord
  has_many :applications
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :rememberable

  belongs_to :role

  has_many :applications
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_application, only: %i[edit show update destroy delete_attachment_collection]

  def index
    @applications = Application.all
  end

  def show
    @statuses = Status.all
  end

  def new
    @application = Application.new
  end

  def create
    @application = Application.new(application_params)
    @application.user ? email = @application.user.email : email = ""
    if @application.save
      ActionCable.server.broadcast "applications",
        phone: @application.phone,
        address: @application.address,
        region: @application.region.name,
        status_id: @application.status_id,
        status_courier: @application.status.courier,
        status_authorizer: @application.status.authorizer,
        status_supervisor: @application.status.supervisor,
        sputnikid: @application.sputnikid,
        name: @application.name,
        time: @application.time.strftime("%d.%m.%Y"),
        timeslot: @application.timeslot.range,
        id: @application.id,
        courier: email,
        courier_id: @application.user_id,
        color: helpers.label_color(@application.status.id),
        create: true
      head :ok
    end
  end

  def destroy
    @application.destroy
    ActionCable.server.broadcast "applications",
      id: @application.id,
      status_id: @application.status_id,
      delete: true
    head :ok
  end

  def edit
    respond_to do |format|
      format.js { render action: "edit.js.erb" }
    end
  end

  def update
    @application.update(application_params)
    stream_application
  end

  def delete_image_attachment
    @application_image = ActiveStorage::Attachment.find(params[:id])
    @application_image.purge_later

    respond_to do |format|
      format.js { render action: "delete_photo.js.erb", :locals => {:id => params[:id]} }
    end
  end

  def delete_attachment_collection
    ActiveStorage::Attachment.where(name: "agreement_photos", record_id: params[:id]).each do |attachment|
      attachment.purge_later
    end
    respond_to do |format|
      format.js
    end
  end

  private

  def find_application
    @application = Application.find(params[:id])
  end

  def application_params
    params.require(:application).permit(:name, :address, :phone, :region, :status_id, :card,
                                        :time, :timeslot_id, :sputnikid, :user_id, :region_id,
                                        :passport_photo, :registration, :client_passport,
                                        :loan_agreement, :asp_agreement, :third_party_agreement,
                                        :pd_agreement, agreement_photos: [])
  end

  def stream_application
    ActionCable.server.broadcast "applications",
                                 phone: @application.phone,
                                 card: @application.card,
                                 region: @application.region.name,
                                 email: @application.user.email,
                                 address: @application.address,
                                 status_courier: @application.status.courier,
                                 status_authorizer: @application.status.authorizer,
                                 status_supervisor: @application.status.supervisor,
                                 status_id: @application.status_id,
                                 sputnikid: @application.sputnikid,
                                 name: @application.name,
                                 time: @application.time.strftime("%d.%m.%Y"),
                                 timeslot: @application.timeslot.range,
                                 id: @application.id,
                                 courier_id: @application.user_id,
                                 color: helpers.label_color(@application.status_id),
                                 update: true,
                                 role: current_user.role_id,
                                 user_id: current_user.id
    head :ok
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!

  def courier_home
    @applications = Application.where("user_id = ? AND status_id between ? and ?", current_user.id, 2, 12)
  end

  def authorizer_dashboard
    @applications = Application.all
    respond_to do |format|
      format.html
      format.js { render action: "edit.js.erb" }
    end
  end

  def supervisor_dashboard
    @applications = Application.all
    @application = Application.new
    respond_to do |format|
      format.html
      format.js { render action: "edit.js.erb" }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authorizer_helper.rb
module AuthorizerHelper
  def meeting_confirmed
    @applications.where(status_id: 4)
  end

  def verificated
    @applications.where(status_id: 6)
  end

  def check_photo
    @applications.where(status_id: 8)
  end

  def attach_card
    @applications.where(status_id: 11)
  end

  def postpone
    @applications.where(status_id: 13)
  end
end

app/helpers/courier_helper.rb
module CourierHelper
  def label_color(status)
    return "teal" if status == 2
    return "teal" if status == 6
    return "green" if status == 3
    return "purple" if status == 4
    return "olive" if status == 5
    return "blue" if status == 7
    return "grey" if status == 8
    return "red" if status == 9
    return "pink" if status == 10
    return "orange" if status == 11
    return "brown" if status == 12
  end
end

app/helpers/supervisor_helper.rb
module SupervisorHelper
  def applications_to_distribute
    @applications.where(status_id: 1)
  end

  def documents_to_hand_out
    @applications.where(status_id: 2)
  end

  def processing
    @applications.where("status_id BETWEEN ? AND ?", 3, 11)
  end

  def collect_documents
    @applications.where(status_id: 12)
  end
end

app/views/applications/_new.html.erb
<div class="margin-bottom-small">
  <div class="ui centered grid">
    <div class="ui header">Новая заявка</div>
  </div>
</div>
<%= form_for @application, :html => {class: 'ui form'}, remote: true do |f| %>
  <div class="field">
    <label for="sputnikid">Номер договора</label>
    <%= f.text_field :sputnikid, id: 'sputnikid', placeholder: 'Номер договора', required: true %>
  </div>

  <div class="field">
    <label for="address">Адрес</label>
    <%= f.text_field :address, id: 'address', placeholder: 'Адрес', required: true  %>
  </div>

  <div class="field">
    <label for="name">ФИО</label>
    <%= f.text_field :name, id: 'name', placeholder: 'ФИО', required: true   %>
  </div>

  <div class="field">
    <label for="phone">Телефон</label>
    <%= f.text_field :phone, id: 'phone', placeholder: 'Телефон', required: true  %>
  </div>

  <div class="two fields">
    <div class="field">
      <label for="time">Дата</label>
      <%= f.date_field :time, id: 'time', class: 'datepicker' %>
    </div>
    <div class="field">
      <label for="timeslot">Время</label>
      <%= f.collection_select(:timeslot_id, Timeslot.all, :id, :range, {}, {class: 'ui fluid dropdown'}) %>
    </div>
  </div>

  <div class="field">
    <label for="courier">Курьер</label>
    <%= f.collection_select(:user_id, User.where(role_id: 1), :id, :email, { include_blank: true }, {class: 'ui fluid dropdown'} )  %>
  </div>

  <%= f.hidden_field :status_id, value: 1, class: 'new-app-status' %>
  <%= f.hidden_field :region_id, value: 1 %>

  <div class="field">
    <%= f.submit "Создать", class: 'ui button yellow big fluid' %>
  </div>
<% end %>

app/views/applications/_status_collect_documents.html.erb
<div class="wait">
  <div class="wait__text">
    <p class="wait__p">Получите документы по адресу:</p>
    <p class="wait__p">ул. Волгоградский проспект, 43</p>
  </div>
  <div class="wait__button">
    <%= link_to 'Вернуться назад', root_path, class: 'ui button purple fluid massive' %>
  </div>
</div>

app/views/applications/_status_courier_card.html.erb
<div class="card-form">
  <div class="card-form__header">
    Привяжите карту банка
  </div>
  <div class="ui form">
      <div class="field">
        <%= form_for @application, :html => {class: 'ui form massive'} do  |t| %>
          <%= t.hidden_field :status_id, value: 11 %>
          <%= t.text_field :card, placeholder: 'Номер карты', class: 'big', required: true %>
          <div class="margin-top-tiny">
            <%= t.submit "Привязать карту", class: "ui button massive primary fluid" %>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/applications/_status_return_documents.html.erb
<div class="app-card">
  <span class="ui header">Верните документы по адресу: ул. Волгоградский проспект, 43</span>
</div>

app/views/applications/_status_verification_application_courier.html.erb
<div class="app-card">
  <div class="ui centered grid">
    <div class="ui centered row">
      <div class="ui checkbox adequate">
        <input type="checkbox" name="adequate">
        <label>Клиент трезв и адекватен</label>
      </div>
    </div>

    <div class="ui centered row">
      <div class="ui checkbox passport_photo">
        <input type="checkbox" name="passport_photo">
        <label>Фото в паспорте соответствует человеку</label>
      </div>
    </div>

    <div class="ui centered row">
      <div class="ui checkbox passport_data">
        <input type="checkbox" name="passport_data">
        <label>Данные паспорта верные</label>
      </div>
    </div>

     <div class="ui centered row">
       <div class="verification_button hidden">
          <%= form_for application, remote: true do |t| %>
            <%= t.hidden_field :status_id, value: 6  %>
            <%= t.submit "ВЕРИФИЦИРОВАТЬ", class: "vb button blue massive ui" %>
          <% end %>
       </div>
       <div class="unverified_button">
         <div class="vb button red massive ui cancel-app">Отказать</div>
       </div>
     </div>
  </div>
</div>

<div class="ui large modal cancel">
  <div class="header">
    <div class="ui centered grid">
      <div class="app-approval">ДАННОЕ ДЕЙСТВИЕ ОТМЕНИТ ЗАЯВКУ И УДАЛИТ ЕЁ С ВАШЕГО ТЕЛЕФОНА</div>
      <div class="ui centered row">ОТМЕНИТЬ ЗАЯВКУ?</div>
    </div>
  </div>
  <div class="content">
    <div class="ui three column centered grid">
      <div class="column">
        <div class="button ui red huge app-cancel-button modal-button">НЕТ</div>
      </div>
      <div class="column">
          <%= form_for application, remote: true do |t| %>
            <%= t.hidden_field :status_id, value: 15 %>
            <%= t.submit "ДА", class: "button ui basic huge modal-button" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/applications/_status_wait_operator.html.erb
<div class="wait">
  <div class="wait__text">
    <span>Ожидание оператора</span>
  </div>
  <div class="wait__button">
    <%= link_to 'Вернуться назад', root_path, class: 'ui button purple fluid massive' %>
  </div>
</div>

app/views/pages/authorizer_dashboard.html.erb
<div class="supervisor-menu-container">
  <div class="logo-dashboard">
    <%= image_tag 'logo.png', width: "200px" %>
  </div>
</div>

<div class="popup-edit" id="popup">
  <div class="popup-edit__content">
    <div class="popup-edit__form">
      <a href="#" data-turbolinks="false" class="popup-edit__close">&times;</a>
    </div>
  </div>
</div>

<div class="ui grid">
  <div class="margin-top-medium my-tabs">
    <input id="auth-meeting" type="radio" name="tabs" class="tab-input" checked>
    <label for="auth-meeting" class="tab-label">Подтвердить в спутнике <span class="ui orange circular label small"><%= meeting_confirmed.size %></span></label>

    <input id="auth-verificated" type="radio" name="tabs" class="tab-input">
    <label for="auth-verificated" class="tab-label">Верифицировать в спутнике</label>

    <input id="auth-photo" type="radio" name="tabs" class="tab-input">
    <label for="auth-photo" class="tab-label">Проверить фото</label>

    <input id="auth-card" type="radio" name="tabs" class="tab-input">
    <label for="auth-card" class="tab-label">Привязать карту</label>

    <input id="auth-postpone" type="radio" name="tabs" class="tab-input">
    <label for="auth-postpone" class="tab-label">Перенести встречу</label>

    <section class="authorizer-section" id="auth-meeting-content">
      <table class="ui striped selectable table" id="authorizer-meeting">
        <thead>
          <tr>
            <th>ID</th>
            <th>Номер договора</th>
            <th>ФИО</th>
            <th>Телефон</th>
            <th>Адрес</th>
            <th>Курьер</th>
            <th>Дата</th>
            <th>Время</th>
            <th class="center aligned">Действие</th>
          </tr>
        </thead>
        <tbody>
        <% meeting_confirmed.each do |app| %>
          <tr class="table-app-<%= app.id %>">
            <td><%= app.id %></td>
            <td><%= app.sputnikid %></td>
            <td><%= app.name %></td>
            <td><%= app.phone %></td>
            <td><%= app.address %></td>
            <td><%= app.user.email %></td>
            <td><%= app.time.strftime("%d.%m.%Y") %></td>
            <td><%= app.timeslot.range %></td>
            <td class="center aligned">
              <%= form_for app, :html => {class: 'form-table'}, remote: true do  |t| %>
                <%= t.hidden_field :status_id, value: 5 %>
                <%= t.submit "Подтверждено", class: "button ui blue mini" %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </section>

    <section class="authorizer-section" id="auth-verificated-content">
      <table class="ui striped selectable table" id="authorizer-verification">
        <thead>
          <tr>
            <th>ID</th>
            <th>Номер договора</th>
            <th>ФИО</th>
            <th>Телефон</th>
            <th>Адрес</th>
            <th>Курьер</th>
            <th>Дата</th>
            <th>Время</th>
            <th class="center aligned">Действие</th>
          </tr>
        </thead>
        <tbody>
        <% verificated.each do |app| %>
          <tr class="table-app-<%= app.id %>">
            <td><%= app.id %></td>
            <td><%= app.sputnikid %></td>
            <td><%= app.name %></td>
            <td><%= app.phone %></td>
            <td><%= app.address %></td>
            <td><%= app.user.email %></td>
            <td><%= app.time.strftime("%d.%m.%Y") %></td>
            <td><%= app.timeslot.range %></td>
            <td class="center aligned">
              <%= form_for app, :html => {class: 'form-table'}, remote: true do  |t| %>
                <%= t.hidden_field :status_id, value: 7 %>
                <%= t.submit "Подтверждено", class: "button ui blue mini" %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </section>

    <section class="authorizer-section" id="auth-photo-content">
      <table class="ui striped selectable table" id="authorizer-photo">
        <thead>
          <tr>
            <th>ID</th>
            <th>Номер договора</th>
            <th>ФИО</th>
            <th>Телефон</th>
            <th>Адрес</th>
            <th>Курьер</th>
            <th>Дата</th>
            <th>Время</th>
            <th class="center aligned">Действие</th>
          </tr>
        </thead>
        <tbody>
        <% check_photo.each do |app| %>
          <tr class="table-app-<%= app.id %>">
            <td><%= app.id %></td>
            <td><%= app.sputnikid %></td>
            <td><%= app.name %></td>
            <td><%= app.phone %></td>
            <td><%= app.address %></td>
            <td><%= app.user.email %></td>
            <td><%= app.time.strftime("%d.%m.%Y") %></td>
            <td><%= app.timeslot.range %></td>
            <td class="center aligned">
              <%= link_to 'Проверить фото', application_path(app), class: "button ui blue mini" %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </section>

    <section class="authorizer-section" id="auth-card-content">
      <table class="ui striped selectable table" id="authorizer-card">
        <thead>
          <tr>
            <th>ID</th>
            <th>Номер договора</th>
            <th>ФИО</th>
            <th>Телефон</th>
            <th>Адрес</th>
            <th>Курьер</th>
            <th>Дата</th>
            <th>Время</th>
            <th>Карта</th>
            <th class="center aligned">Действие</th>
          </tr>
        </thead>
        <tbody>
        <% attach_card.each do |app| %>
          <tr class="table-app-<%= app.id %>">
            <td><%= app.id %></td>
            <td><%= app.sputnikid %></td>
            <td><%= app.name %></td>
            <td><%= app.phone %></td>
            <td><%= app.address %></td>
            <td><%= app.user.email %></td>
            <td><%= app.time.strftime("%d.%m.%Y") %></td>
            <td><%= app.timeslot.range %></td>
            <td><%= app.card %></td>
            <td class="center aligned">
              <%= form_for app, :html => {class: 'form-table'}, remote: true do  |t| %>
                <%= t.hidden_field :status_id, value: 12 %>
                <%= t.submit "Карта привязана", class: "button ui blue mini" %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </section>

    <section class="authorizer-section" id="auth-postpone-content">
      <table class="ui striped selectable table" id="authorizer-postpone">
        <thead>
          <tr>
            <th>ID</th>
            <th>Номер договора</th>
            <th>ФИО</th>
            <th>Телефон</th>
            <th>Адрес</th>
            <th>Курьер</th>
            <th>Дата</th>
            <th>Время</th>
            <th class="center aligned">Действие</th>
          </tr>
        </thead>
        <tbody>
        <% postpone.each do |app| %>
          <tr class="table-app-<%= app.id %>">
            <td><%= app.id %></td>
            <td><%= app.sputnikid %></td>
            <td><%= app.name %></td>
            <td><%= app.phone %></td>
            <td><%= app.address %></td>
            <td><%= app.user.email %></td>
            <td><%= app.time.strftime("%d.%m.%Y") %></td>
            <td><%= app.timeslot.range %></td>
            <td class="center aligned">
              <%= link_to 'Перенести', edit_application_path(app), remote: true, class: 'ui button small primary' %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </section>
  </div>
</div>

app/views/pages/courier_home.html.erb
<div class="courier-home">
</div>

<div class="container-app">
</div>

<div class="page-name" data-page="courier-home">
</div>

<div class="navbar-courier">
    <%= render 'shared/courier_navbar' %>
    <div class="app-container">
      <div class="ui header">Мои заявки</div>
    </div>
</div>

<%= content_tag(:div, :class => "cards courier-id-#{current_user.id}") do %>
  <% @applications.each do |app| %>
    <%= link_to application_path(app), class: "ui card card-courier", id: "courier-app-#{app.id}" do %>
      <div class="content">
        <div class="header">
          <%= app.name %>
          <%= content_tag(:span, app.status.courier, :class => "card-courier notice right floated ui label card-courier #{label_color(app.status.id)}") %>
        </div>
        <div class="description">
          <p><%= app.address %></p>
          <p>Тел: <%= app.phone %></p>
          <p>ID: <%= app.id %></p>
        </div>
      </div>
      <div class="extra content">
        <p>Встреча: <%= app.time.strftime("%d.%m.%Y") %>, время: <%= app.timeslot.range %></p>
      </div>
    <% end %>
  <% end %>
<% end %>

<div class="side-menu"></div>
<div class="overlay"></div>

app/views/pages/supervisor_dashboard.html.erb
<div class="supervisor-menu-container">
  <a href="#popup-new" class="btn-new-app" data-turbolinks="false">
    <div class="btn-new-app__content">
      +
    </div>
  </a>

  <div class="logo-dashboard">
    <%= image_tag 'logo.png', width: "200px" %>
  </div>
</div>

<div class="popup-new" id="popup-new">
  <div class="popup-new__content">
    <div class="popup-new__form">
      <%= render partial: 'applications/new', locals: {application: @application }%>
      <a href="#" data-turbolinks="false" class="popup-new__close">&times;</a>
    </div>
  </div>
</div>

<div class="popup-edit" id="popup-edit">
  <div class="popup-edit__content">
    <div class="popup-edit__form">
      <a href="#" data-turbolinks="false" class="popup-edit__close">&times;</a>
    </div>
  </div>
</div>

<div class="ui grid">
  <div class="margin-top-medium my-tabs">
    <input id="sp-distribute" type="radio" name="tabs" class="tab-input" checked>
    <label for="sp-distribute" class="tab-label">Распределить</label>

    <input id="sp-hand-out-documents" type="radio" name="tabs" class="tab-input">
    <label for="sp-hand-out-documents" class="tab-label">Выдать документы</label>

    <input id="sp-processing" type="radio" name="tabs" class="tab-input">
    <label for="sp-processing" class="tab-label">В работе</label>

    <input id="sp-collect-documents" type="radio" name="tabs" class="tab-input">
    <label for="sp-collect-documents" class="tab-label">Забрать документы</label>

    <section class="supervisor-section" id="sp-distribute-content">
      <table class="ui striped selectable table" id="app-to-distribute">
        <thead>
          <tr>
            <th>ID</th>
            <th>Номер договора</th>
            <th>ФИО</th>
            <th>Телефон</th>
            <th>Адрес</th>
            <th>Курьер</th>
            <th>Дата</th>
            <th>Время</th>
            <th class="center aligned">Действие</th>
          </tr>
        </thead>
        <tbody>
        <% applications_to_distribute.each do |app| %>
          <tr class="table-app-<%= app.id %>">
            <td><%= app.id %></td>
            <td><%= app.sputnikid %></td>
            <td><%= app.name %></td>
            <td><%= app.phone %></td>
            <td><%= app.address %></td>
            <td>Курьер не выбран</td>
            <td><%= app.time.strftime("%d.%m.%Y") %></td>
            <td><%= app.timeslot.range %></td>
            <td class="center aligned">
              <%= link_to 'Распределить', edit_application_path(app), remote: true, class: 'ui button small green' %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </section>

    <section class="supervisor-section" id="sp-hand-out-content">
      <table class="ui striped selectable table" id="app-to-hand-out">
        <thead>
          <tr>
            <th>ID</th>
            <th>Номер договора</th>
            <th>ФИО</th>
            <th>Телефон</th>
            <th>Адрес</th>
            <th>Курьер</th>
            <th>Дата</th>
            <th>Время</th>
            <th class="center aligned">Действие</th>
          </tr>
        </thead>
        <tbody class='documents-to-hand-out'>
        <% documents_to_hand_out.each do |app| %>
          <tr class="table-app-<%= app.id %>">
            <td><%= app.id %></td>
            <td><%= app.sputnikid %></td>
            <td><%= app.name %></td>
            <td><%= app.phone %></td>
            <td><%= app.address %></td>
            <td><%= app.user.email %></td>
            <td><%= app.time.strftime("%d.%m.%Y") %></td>
            <td><%= app.timeslot.range %></td>
            <td class="center aligned position-relative">
              <%= form_for app, :html => {class: 'form-table'}, remote: true do  |t| %>
                <%= t.hidden_field :status_id, value: 3 %>
                <%= t.submit "Документы выданы", class: "button ui blue mini" %>
              <% end %>
              <%= link_to edit_application_path(app), remote: true do %>
                <i class="icon-table far fa-edit"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </section>

    <section class="supervisor-section" id="sp-processing-content">
      <table class="ui striped selectable table" id="app-processing">
        <thead>
          <tr>
            <th>ID</th>
            <th>Номер договора</th>
            <th>ФИО</th>
            <th>Телефон</th>
            <th>Адрес</th>
            <th>Курьер</th>
            <th>Дата</th>
            <th>Время</th>
            <th>Статус</th>
          </tr>
        </thead>
        <tbody class='documents-to-hand-out'>
        <% processing.each do |app| %>
          <tr class="table-app-<%= app.id %>">
            <td><%= app.id %></td>
            <td><%= app.sputnikid %></td>
            <td><%= app.name %></td>
            <td><%= app.phone %></td>
            <td><%= app.address %></td>
            <td><%= app.user.email %></td>
            <td><%= app.time.strftime("%d.%m.%Y") %></td>
            <td><%= app.timeslot.range %></td>
            <td><%= app.status.supervisor %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </section>

    <section class="supervisor-section" id="sp-collect-content">
      <table class="ui striped selectable table" id="app-collect-documents">
        <thead>
          <tr>
            <th>ID</th>
            <th>Номер договора</th>
            <th>ФИО</th>
            <th>Телефон</th>
            <th>Адрес</th>
            <th>Курьер</th>
            <th>Дата</th>
            <th>Время</th>
            <th class="center aligned">Действие</th>
          </tr>
        </thead>
        <tbody class='documents-to-hand-out'>
        <% collect_documents.each do |app| %>
          <tr class="table-app-<%= app.id %>">
            <td><%= app.id %></td>
            <td><%= app.sputnikid %></td>
            <td><%= app.name %></td>
            <td><%= app.phone %></td>
            <td><%= app.address %></td>
            <td><%= app.user.email %></td>
            <td><%= app.time.strftime("%d.%m.%Y") %></td>
            <td><%= app.timeslot.range %></td>
            <td class="center aligned">
              <%= form_for app, :html => {class: 'form-table'}, remote: true do  |t| %>
                <%= t.hidden_field :status_id, value: 14 %>
                <%= t.submit "Документы получены", class: "button ui blue small" %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </section>

  </div>
</div>

app/views/shared/_cards_grid.html.erb
<%= content_tag :div, class: "ui grid operator-grid", data: { quantity: "#{app_group.size}" } do %>
  <% app_group.each do |app| %>
    <%= content_tag :div, class: "segment app-id-#{app.id}" do %>
      <div class="ui card operator-card">
        <div class="content">
          <div class="header">
            <%= app.name %>
          </div>
          <div class="description">
            <p>ID заявки: <%= app.id %></p>
            <p><%= app.status.operator %></p>
            <p><b>Телефон:</b> <%= app.phone %></p>
            <p><b>Адрес: </b><%= app.address %></p>
            <p><b>Номер в спутнике: </b> <%= app.sputnikid %></p>
            <p><%= link_to 'Delete', application_path(app), method: :delete, remote: true %></p>
            <p><%= link_to 'Редактировать', edit_application_path(app) %><p>
            <p></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>